---
services:
  mongo-{{ release.name }}:
    image: "{{ values.image.mongo.repository }}:{{ values.image.mongo.tag }}"
    hostname: "mongo-{{ release.name }}"
    container_name: "mongo-{{ release.name }}"
    ports:
    {% for service in values.service.mongo %}
     - "{{ service.node_port }}:{{ service.container_port }}"
    {% endfor %}
    environment:
    {% for env in values.environment_variables.mongo %}
      {{ env.name }}: "{{ env.value }}"
    {% endfor %}
    volumes:
      - "mongo-data-db-{{ release.name }}:/data/db"
      - "mongo-data-configdb-{{ release.name }}:/data/configdb"
