---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  {{- if .Release.Namespace | ne "default" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- else if .Values.namespace | ne "default" }}
  namespace: {{ .Values.namespace | quote }}
  {{- end }}
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: "{{ .Release.Name }}-{{ .Chart.Name }}"
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        {{- toYaml .Values.environmentVariables | nindent 8 }}
        {{- if .Values.resources }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.limits.memory | quote }}
            cpu: {{ .Values.resources.limits.cpu | quote }}
        {{- end}}
        volumeMounts:
        - name: "{{ .Release.Name }}-{{ .Chart.Name }}-db"
          mountPath: "/data/db"
        - name: "{{ .Release.Name }}-{{ .Chart.Name }}-configdb"
          mountPath: "/data/configdb"
      volumes:
      - name: "{{ .Release.Name }}-{{ .Chart.Name }}-db"
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-{{ .Chart.Name }}-db-claim"
      - name: "{{ .Release.Name }}-{{ .Chart.Name }}-configdb"
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-{{ .Chart.Name }}-configdb-claim"
