---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  {{- if .Release.Namespace | ne "default" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- else if .Values.namespace | ne "default" }}
  namespace: {{ .Values.namespace | quote }}
  {{- end }}
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: "{{ .Release.Name }}-{{ .Chart.Name }}"
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.jupyternb.port }}
        - containerPort: {{ .Values.service.java1.port }}
        - containerPort: {{ .Values.service.java2.port }}
        volumeMounts:
        - name: "{{ .Release.Name }}-{{ .Chart.Name }}-data"
          mountPath: "/data"
        {{- if .Values.resources }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.limits.memory | quote }}
            cpu: {{ .Values.resources.limits.cpu | quote }}
        {{- end}}
      volumes:
      - name: "{{ .Release.Name }}-{{ .Chart.Name }}-data"
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-{{ .Chart.Name }}-data-claim"
