---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "batfish-service"
spec:
  type: {{ .Values.service.type | quote }}
  ports:
  - port: {{ .Values.service.jupyternb.port }}             # Port apps in cluster use
    targetPort: {{ .Values.service.jupyternb.port }}        # Port to connect to container
    nodePort: {{ .Values.service.jupyternb.nodePort }}        # Port to expose on the nodes
    protocol: "TCP"
    name: {{ .Values.service.jupyternb.name | quote }}
  - port: {{ .Values.service.java1.port }}              # Port apps in cluster use
    targetPort: {{ .Values.service.java1.port }}         # Port to connect to container
    nodePort: {{ .Values.service.java1.nodePort }}        # Port to expose on the nodes
    protocol: "TCP"
    name: {{ .Values.service.java1.name | quote }}
  - port: {{ .Values.service.java2.port }}               # Port apps in cluster use
    targetPort: {{ .Values.service.java2.port }}       # Port to connect to container
    nodePort: {{ .Values.service.java2.nodePort }}        # Port to expose on the nodes
    protocol: "TCP"
    name: {{ .Values.service.java2.name | quote }}
  selector:
    app: "batfish"
