---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-server
spec:
  type: LoadBalancer
  ports:
  - port: 8111
    targetPort: 8111
    name: teamcity-server-gui
  selector:
    app: teamcity-server
