---
apiVersion: v1
kind: Service
metadata:
  name: registry-browser-service-nodeport
spec:
  type: NodePort
  ports:
  - port: 8088             # Port apps in cluster use
    targetPort: 8080       # Port to connect to container
    nodePort: 31112        # Port to expose on the nodes
    protocol: TCP
  selector:
    app: registry-browser
