---
services:
  grafana-{{ release.name }}:
    image: "{{ values.image.repository }}:{{ values.image.tag }}"
    hostname: "grafana-{{ release.name }}"
    container_name: "grafana-{{ release.name }}"
    ports:
    {% for service in values.service %}
     - "{{ service.node_port }}:{{ service.container_port }}"
    {% endfor %}
    volumes:
      - "grafana-data-{{ release.name }}:/var/lib/grafana"
      - "grafana-logs-{{ release.name }}:/var/log/grafana"
