---
# Default values for kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  registry: "docker.io"
  pullPolicy: "Always"
  broker:
    repository: "confluentinc/cp-server"
    tag: "latest"
  controlCenter:
    repository: "confluentinc/cp-enterprise-control-center"
    tag: "latest"
  restProxy:
    repository: "confluentinc/cp-kafka-rest"
    tag: "latest"
  schemaRegistry:
    repository: "confluentinc/cp-schema-registry"
    tag: "latest"
  zooKeeper:
    repository: "confluentinc/cp-zookeeper"
    tag: "latest"

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  controlCenter:
    type: "LoadBalancer"
    port: 9021
  restProxy:
    type: "LoadBalancer"
    port: 8082
  schemaRegistry:
    type: "LoadBalancer"
    port: 8081
  zooKeeper:
    type: "LoadBalancer"
    port: 2181

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #  controlCenter:
  #    limits:
  #      cpu: "1"
  #      memory: "2Gi"
  #    requests:
  #      cpu: "500m"
  #      memory: "1.5Gi"
  #  restProxy:
  #    limits:
  #      cpu: "1"
  #      memory: "256Mi"
  #    requests:
  #      cpu: "500m"
  #      memory: "128Mi"
  #  schemaRegistry:
  #    limits:
  #      cpu: "1"
  #      memory: "1Gi"
  #    requests:
  #      cpu: "500m"
  #      memory: "512Mi"
  #  zooKeeper:
  #    limits:
  #      cpu: "1"
  #      memory: "256Mi"
  #    requests:
  #      cpu: "500m"
  #      memory: "128Mi"

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
