---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "grafana-service"
spec:
  type: "NodePort"
  ports:
  - port: {{ .Values.service.port }}               # Port apps in cluster use
    targetPort: {{ .Values.service.port }}         # Port to connect to container
    nodePort: {{ .Values.service.nodePort }}       # Port to expose on the nodes
    protocol: "TCP"
  selector:
    app: "grafana"
