---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "grafana-service"
  {{- if .Release.Namespace | ne "default" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- else if .Values.namespace | ne "default" }}
  namespace: {{ .Values.namespace | quote }}
  {{- end }}
spec:
  type: "NodePort"
  ports:
  - port: {{ .Values.service.port }}               # Port apps in cluster use
    targetPort: {{ .Values.service.port }}         # Port to connect to container
    {{- if .Values.service.type | eq "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}       # Port to expose on the nodes
    {{- end }}
    protocol: "TCP"
  selector:
    app: "grafana"
