---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  {{- if .Release.Namespace | ne "default" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- else if .Values.namespace | ne "default" }}
  namespace: {{ .Values.namespace | quote }}
  {{- end }}
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: "{{ .Release.Name }}-{{ .Chart.Name }}"
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: VAULT_LOCAL_CONFIG
          value: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
        volumeMounts:
        - name: "{{ .Release.Name }}-{{ .Chart.Name }}-logs"
          mountPath: "/vault/logs"
        - name: "{{ .Release.Name }}-{{ .Chart.Name }}-file"
          mountPath: "/vault/file"
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{- if .Values.resources }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.limits.memory | quote }}
            cpu: {{ .Values.resources.limits.cpu | quote }}
        {{- end}}
      volumes:
      - name: "{{ .Release.Name }}-{{ .Chart.Name }}-logs"
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-{{ .Chart.Name }}-logs-claim"
      - name: "{{ .Release.Name }}-{{ .Chart.Name }}-file"
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-{{ .Chart.Name }}-file-claim"
