---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "vault-file-claim"
spec:
  accessModes:
  - "ReadWriteMany"
  volumeMode: "Filesystem"
  resources:
    requests:
      storage: "1Gi"
