---
apiVersion: v1
kind: Service
metadata:
  name: vault-service-nodeport
spec:
  type: NodePort
  ports:
  - port: 8200             # Port apps in cluster use
    targetPort: 8200       # Port to connect to container
    nodePort: 31124        # Port to expose on the nodes
    protocol: TCP
  selector:
    app: vault
