---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  {{- if .Release.Namespace | ne "default" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- else if .Values.namespace | ne "default" }}
  namespace: {{ .Values.namespace | quote }}
  {{- end }}
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: "{{ .Release.Name }}-{{ .Chart.Name }}"
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote}}
        ports:
        - containerPort: {{ .Values.service.ssh.port }}
        - containerPort: {{ .Values.service.https.port }}
        - containerPort: {{ .Values.service.http.port }}
        volumeMounts:
        - name: "{{ .Release.Name }}-{{ .Chart.Name }}-gitlab-etc"
          mountPath: "/etc/gitlab"
        - name: "{{ .Release.Name }}-{{ .Chart.Name }}-gitlab-var-opt"
          mountPath: "/var/opt/gitlab"
        - name: "{{ .Release.Name }}-{{ .Chart.Name }}-gitlab-var-log"
          mountPath: "/var/log/gitlab"
        {{- if .Values.resources }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.limits.memory | quote }}
            cpu: {{ .Values.resources.limits.cpu | quote }}
        {{- end}}
      volumes:
      - name: "{{ .Release.Name }}-{{ .Chart.Name }}-gitlab-etc"
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-{{ .Chart.Name }}-etc-claim"
      - name: "{{ .Release.Name }}-{{ .Chart.Name }}-gitlab-var-opt"
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-{{ .Chart.Name }}-var-opt-claim"
      - name: "{{ .Release.Name }}-{{ .Chart.Name }}-gitlab-var-log"
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-{{ .Chart.Name }}-var-log-claim"
