apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-kafka-latest.yml
      -o ./kafka-latest-k8s/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: broker-3
  name: broker-3
spec:
  ports:
  - name: "9094"
    port: 9094
    targetPort: 9094
  selector:
    io.kompose.service: broker-3
status:
  loadBalancer: {}
