---
apiVersion: v1
kind: Service
metadata:
  name: broker-3
spec:
  type: LoadBalancer
  ports:
  - port: 9094
    targetPort: 9094
    name: broker-3
  - port: 29094
    targetPort: 29094
    name: broker-3-local
  selector:
    app: broker-3
