---
apiVersion: v1
kind: Service
metadata:
  name: control-center-lb
spec:
  type: LoadBalancer
  ports:
  - port: 9021
    targetPort: 9021
    name: control-center
  selector:
    app: control-center
