---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    name: schema-registry
  selector:
    app: schema-registry
