---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    name: control-center
  selector:
    app: schema-registry
