---
apiVersion: v1
kind: Service
metadata:
  name: broker-1
spec:
  type: LoadBalancer
  ports:
  - port: 9092
    targetPort: 9092
    name: broker-1
  - port: 29092
    targetPort: 29092
    name: broker-1-local
  selector:
    app: broker-1
