---
# This is example values file for the template
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "docker.io/library/mongo"
  tag: "8.0.3"

service:
  - node_port: 27017
    container_port: 27017
    name: "mongo-db"

environment_variables:
  - name: "MONGO_INITDB_ROOT_USERNAME"
    value: "root"
  - name: "MONGO_INITDB_ROOT_PASSWORD"
    value: "example"
