---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nautobot-postgresql-claim
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
