---
# Default values for influxdb2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: "docker.io/library/influxdb"
  # This sets the pull policy for images.
  pullPolicy: "Always"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.7.10"

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: "NodePort"
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8086
  nodePort: 31120

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: "1"
  #   memory: "512Mi"
  # requests:
  #   cpu: "500m"
  #   memory: "256Mi"

# Additional volumes on the output Deployment definition.
volumes:
  - name: "influxdb2-var-lib"
    persistentVolumeClaim:
      claimName: "influxdb2-var-lib-claim"
  - name: "influxdb2-etc"
    persistentVolumeClaim:
      claimName: "influxdb2-etc-claim"

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: "influxdb2-var-lib"
    mountPath: "/var/lib/influxdb2"
  - name: "influxdb2-etc"
    mountPath: "/etc/influxdb2"
