---
apiVersion: v1
kind: Service
metadata:
  name: nautobot-service-nodeport
spec:
  type: NodePort
  ports:
  - port: 8000             # Port apps in cluster use
    targetPort: 8000       # Port to connect to container
    nodePort: 31123        # Port to expose on the nodes
    protocol: TCP
  selector:
    app: nautobot
