---
services:
  nautobot-{{ release.name }}:
    image: "{{ values.image.nautobot.repository }}:{{ values.image.nautobot.tag }}"
    container_name: "nautobot-{{ release.name }}"
    environment:
      NAUTOBOT_ALLOWED_HOSTS: "*"
      NAUTOBOT_BANNER_TOP: "Local"
      NAUTOBOT_CHANGELOG_RETENTION: 0
      NAUTOBOT_CONFIG: "/opt/nautobot/nautobot_config.py"
      NAUTOBOT_DB_HOST: "nautobot-db-{{ release.name }}"
      NAUTOBOT_DB_NAME: "{{ values.config.nautobot_db_name }}"
      NAUTOBOT_DB_USER: "{{ values.secrets.nautobot_db_user }}"
      NAUTOBOT_DEBUG: "True"
      NAUTOBOT_DJANGO_EXTENSIONS_ENABLED: "False"
      NAUTOBOT_DJANGO_TOOLBAR_ENABLED: "False"
      NAUTOBOT_HIDE_RESTRICTED_UI: "True"
      NAUTOBOT_LOG_LEVEL: "{{ values.config.nautobot_log_level }}"
      NAUTOBOT_METRICS_ENABLED: "True"
      NAUTOBOT_NAPALM_TIMEOUT: 5
      NAUTOBOT_MAX_PAGE_SIZE: 0
      NAUTOBOT_REDIS_HOST: "nautobot-redis-{{ release.name }}"
      NAUTOBOT_REDIS_PORT: 6379
      NAUTOBOT_CREATE_SUPERUSER: "false"
      NAUTOBOT_DB_PASSWORD: "{{ values.secrets.nautobot_db_password }}"
      NAUTOBOT_NAPALM_USERNAME: ""
      NAUTOBOT_NAPALM_PASSWORD: ""
      NAUTOBOT_REDIS_PASSWORD: "{{ values.secrets.nautobot_redis_password }}"
      NAUTOBOT_SECRET_KEY: "012345678901234567890123456789012345678901234567890123456789"
      NAUTOBOT_SUPERUSER_NAME: "admin"
      NAUTOBOT_SUPERUSER_EMAIL: "admin@example.com"
      NAUTOBOT_SUPERUSER_PASSWORD: "admin"
      NAUTOBOT_SUPERUSER_API_TOKEN: "0123456789abcdef0123456789abcdef01234567"
      NAUTOBOT_CACHEOPS_REDIS: "redis://:{{ values.secrets.nautobot_redis_password }}@nautobot-redis-{{ release.name }}:6379/1"
    ports:
    {% for service in values.service.nautobot %}
     - "{{ service.node_port }}:{{ service.container_port }}"
    {% endfor %}
    tty: true
    healthcheck:
      interval: "30s"
      timeout: "10s"
      start_period: "60s"
      retries: 3
      test:
        - "CMD"
        - "true"  # Due to layering, disable: true won't work. Instead, change the test
    depends_on:
      - "nautobot-db-{{ release.name }}"
      - "nautobot-redis-{{ release.name }}"
