---
services:
  nautobot-celery-worker-{{ release.name }}:
    image: "{{ values.image.nautobot.repository }}:{{ values.image.nautobot.tag }}"
    container_name: "nautobot-celery-worker-{{ release.name }}"
    environment:
      NAUTOBOT_ALLOWED_HOSTS: "*"
      NAUTOBOT_BANNER_TOP: "{{ values.config.nautobot_banner_top }}"
      NAUTOBOT_CHANGELOG_RETENTION: 0
      NAUTOBOT_CONFIG: "/opt/nautobot/nautobot_config.py"
      NAUTOBOT_DB_HOST: "nautobot-db-{{ release.name }}"
      NAUTOBOT_DB_NAME: "{{ values.config.nautobot_db_name }}"
      NAUTOBOT_DB_USER: "{{ values.secrets.nautobot_db_user }}"
      NAUTOBOT_DEBUG: "True"
      NAUTOBOT_DJANGO_EXTENSIONS_ENABLED: "False"
      NAUTOBOT_DJANGO_TOOLBAR_ENABLED: "False"
      NAUTOBOT_HIDE_RESTRICTED_UI: "True"
      NAUTOBOT_LOG_LEVEL: "{{ values.config.nautobot_log_level }}"
      NAUTOBOT_METRICS_ENABLED: "True"
      NAUTOBOT_NAPALM_TIMEOUT: 5
      NAUTOBOT_MAX_PAGE_SIZE: 0
      NAUTOBOT_REDIS_HOST: "nautobot-redis-{{ release.name }}"
      NAUTOBOT_REDIS_PORT: 6379
      NAUTOBOT_CREATE_SUPERUSER: "{{ values.config.nautobot_create_superuser }}"
      NAUTOBOT_DB_PASSWORD: "{{ values.secrets.nautobot_db_password }}"
      NAUTOBOT_NAPALM_USERNAME: "{{ values.secrets.nautobot_napalm_username }}"
      NAUTOBOT_NAPALM_PASSWORD: "{{ values.secrets.nautobot_napalm_password }}"
      NAUTOBOT_REDIS_PASSWORD: "{{ values.secrets.nautobot_redis_password }}"
      NAUTOBOT_SECRET_KEY: "012345678901234567890123456789012345678901234567890123456789"
      NAUTOBOT_SUPERUSER_NAME: "{{ values.secrets.nautobot_superuser_name }}"
      NAUTOBOT_SUPERUSER_EMAIL: "{{ values.secrets.nautobot_superuser_email }}"
      NAUTOBOT_SUPERUSER_PASSWORD: "{{ values.secrets.nautobot_superuser_password }}"
      NAUTOBOT_SUPERUSER_API_TOKEN: "{{ values.secrets.nautobot_superuser_api_token }}"
      NAUTOBOT_CACHEOPS_REDIS: "redis://:{{ values.secrets.nautobot_redis_password }}@nautobot-redis-{{ release.name }}:6379/1"
      NAUTOBOT_INSTALLATION_METRICS_ENABLED: "{{ values.config.nautobot_installation_metrics_enabled }}"
      NAUTOBOT_CORS_ALLOW_ALL_ORIGINS: "{{ values.config.nautobot_cors_allow_all_origins }}"
      {% if values.config.nautobot_csrf_trusted_origins %}
      NAUTOBOT_CSRF_TRUSTED_ORIGINS: "{{ values.config.nautobot_csrf_trusted_origins }}"
      {% endif %}
    tty: true
    entrypoint:
      - "sh"
      - "-c"  # this is to evaluate the $NAUTOBOT_LOG_LEVEL from the env
      - "nautobot-server celery worker -l {{ values.config.nautobot_log_level }} --events"  ## $$ because of docker-compose
    depends_on:
      nautobot-{{ release.name }}:
        condition: "service_healthy"
    healthcheck:
      interval: "30s"
      timeout: "10s"
      start_period: "30s"
      retries: 3
      test:
        - "CMD"
        - "bash"
        - "-c"
        - "nautobot-server celery inspect ping --destination celery@nautobot-celery-worker-{{ release.name }}"  ## $$ because of docker-compose
