---
services:
  rest-proxy-{{ release.name }}:
    image: "{{ values.image.registry }}/{{ values.image.rest_proxy.repository }}:{{ values.image.rest_proxy.tag }}"
    ports:
      - "{{ values.service.rest_proxy.node_port }}:{{ values.service.rest_proxy.container_port }}"
    depends_on:
      - "zookeeper-{{ release.name }}"
      - "broker-1-{{ release.name }}"
      - "broker-2-{{ release.name }}"
      - "broker-3-{{ release.name }}"
      - "schema-registry-{{ release.name }}"
    hostname: "rest-proxy-{{ release.name }}"
    container_name: "rest-proxy-{{ release.name }}"
    environment:
      KAFKA_REST_HOST_NAME: "rest-proxy-{{ release.name }}"
      KAFKA_REST_BOOTSTRAP_SERVERS: "broker-1-{{ release.name }}:2{{ values.service.broker_1.container_port }},broker-2-{{ release.name }}:{{ values.service.broker_2.container_port }},broker-3-{{ release.name }}:{{ values.service.broker_3.container_port }}"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:{{ values.service.rest_proxy.container_port }}"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schema-registry-{{ release.name }}:{{ values.service.schema_registry.container_port }}"
