---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-deploy
  labels:
    app: ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: ansible
        image: localhost:32000/ansible-rh:latest
        imagePullPolicy: Always
