---
# This is example values file for the template
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "docker.io/sebp/elk"
  tag: "8.15.1"

service:
  - node_port: 5601
    container_port: 5601
    name: "kibana"
  - node_port: 9200
    container_port: 9200
    name: "elasticsearch"
  - node_port: 5044
    container_port: 5044
    name: "logstash"
