--- # Version 2021.9.5.001
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk-deploy
  labels:
    app: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk
  template:
    metadata:
      labels:
        app: elk
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: elk
        image: docker.io/sebp/elk:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5601
        - containerPort: 9200
        - containerPort: 5044
        resources:
          requests:
            memory: "4Gi"
            cpu: "500m"
          limits:
            memory: "8Gi"
            cpu: "1"
