---
apiVersion: v1
kind: Service
metadata:
  name: elk-service-nodeport
spec:
  type: NodePort
  ports:
  - port: 5601             # Port apps in cluster use
    targetPort: 5601       # Port to connect to container
    nodePort: 31114        # Port to expose on the nodes
    protocol: TCP
  - port: 9200             # Port apps in cluster use
    targetPort: 9200       # Port to connect to container
    nodePort: 31115        # Port to expose on the nodes
    protocol: TCP
  - port: 5044             # Port apps in cluster use
    targetPort: 5044       # Port to connect to container
    nodePort: 31116        # Port to expose on the nodes
    protocol: TCP
  selector:
    app: elk
