---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-logs-claim"
  {{- if .Release.Namespace | ne "default" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- else if .Values.namespace | ne "default" }}
  namespace: {{ .Values.namespace | quote }}
  {{- end }}
spec:
  accessModes:
  - "ReadWriteMany"
  volumeMode: "Filesystem"
  resources:
    requests:
      storage: "20Gi"
