---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-service"
  {{- if .Release.Namespace | ne "default" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- else if .Values.global.namespace | ne "default" }}
  namespace: {{ .Values.global.namespace | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    {{- if .Values.service.type | eq "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    protocol: "TCP"
    name: {{ .Values.service.name | quote }}
  selector:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
