---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "teamcity-logs-claim"
spec:
  accessModes:
  - "ReadWriteMany"
  volumeMode: "Filesystem"
  resources:
    requests:
      storage: "20Gi"
