---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "teamcity-service"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    {{- if .Values.service.type | eq "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    protocol: "TCP"
    name: {{ .Values.service.name | quote }}
  selector:
    app: "teamcity"
