---
# Default values for gitlab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: "docker.io/gitlab/gitlab-ce"
  # This sets the pull policy for images.
  pullPolicy: "Always"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: "NodePort"
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  ssh:
    port: 22
    nodePort: 32222
    name: "ssh"
    protocol: "TCP"
  http:
    port: 80
    nodePort: 30080
    name: "http"
    protocol: "TCP"
  https:
    port: 443
    nodePort: 30443
    name: "https"
    protocol: "TCP"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: "2.0"
  #   memory: "4Gi"
  # requests:
  #   cpu: "1.0"
  #   memory: "2Gi"

# Additional volumes on the output Deployment definition.
volumes:
  - name: "gitlab-etc"
    persistentVolumeClaim:
      claimName: "gitlab-etc-claim"
  - name: "gitlab-var-opt"
    persistentVolumeClaim:
      claimName: "gitlab-var-opt-claim"
  - name: "gitlab-var-log"
    persistentVolumeClaim:
      claimName: "gitlab-var-log-claim"

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: "gitlab-etc"
    mountPath: "/etc/gitlab"
  - name: "gitlab-var-opt"
    mountPath: "/var/opt/gitlab"
  - name: "gitlab-var-log"
    mountPath: "/var/log/gitlab"
