---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "nautobot-lab-redis-claim"
spec:
  accessModes:
  - "ReadWriteMany"
  volumeMode: "Filesystem"
  resources:
    requests:
      storage: "5Gi"
