---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "rest-proxy"
  labels:
    app: "rest-proxy"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "rest-proxy"
  strategy: {}
  template:
    metadata:
      labels:
        app: "rest-proxy"
    spec:
      containers:
      - name: "rest-proxy"
        image: "{{ .Values.image.registry }}/{{ .Values.image.restProxy.repository }}:{{ .Values.image.restProxy.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: "KAFKA_REST_BOOTSTRAP_SERVERS"
          value: "broker-1:9092,broker-2:9093,broker-3:9094"
        - name: "KAFKA_REST_HOST_NAME"
          value: "rest-proxy"
        - name: "KAFKA_REST_LISTENERS"
          value: "http://0.0.0.0:{{ .Values.service.restProxy.port }}"
        - name: "KAFKA_REST_SCHEMA_REGISTRY_URL"
          value: "http://schema-registry:{{ .Values.service.schemaRegistry.port }}"
        ports:
        - containerPort: {{ .Values.service.restProxy.port }}
        {{- if .Values.resources }}
        resources:
          requests:
            memory: {{ .Values.resources.restProxy.requests.memory | quote }}
            cpu: {{ .Values.resources.restProxy.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.restProxy.limits.memory | quote }}
            cpu: {{ .Values.resources.restProxy.limits.cpu | quote }}
        {{- end }}
