---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "schema-registry"
  labels:
    app: "schema-registry"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "schema-registry"
  strategy: {}
  template:
    metadata:
      labels:
        app: "schema-registry"
    spec:
      containers:
      - name: "schema-registry"
        image: "{{ .Values.image.registry }}/{{ .Values.image.schemaRegistry.repository }}:{{ .Values.image.schemaRegistry.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: "SCHEMA_REGISTRY_HOST_NAME"
          value: "schema-registry"
        - name: "SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL"
          value: "zookeeper:{{ .Values.service.zooKeeper.port }}"
        - name: "SCHEMA_REGISTRY_LISTENERS"
          value: "http://schema-registry:{{ .Values.service.schemaRegistry.port }}"
        ports:
        - containerPort: {{ .Values.service.schemaRegistry.port }}
        {{- if .Values.resources }}
        resources:
          requests:
            memory: {{ .Values.resources.schemaRegistry.requests.memory | quote }}
            cpu: {{ .Values.resources.schemaRegistry.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.schemaRegistry.limits.memory | quote }}
            cpu: {{ .Values.resources.schemaRegistry.limits.cpu | quote }}
        {{- end }}
