---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "zookeeper"
  {{- if .Release.Namespace | ne "default" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- else if .Values.namespace | ne "default" }}
  namespace: {{ .Values.namespace | quote }}
  {{- end }}
  labels:
    app: "zookeeper"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "zookeeper"
  strategy: {}
  template:
    metadata:
      labels:
        app: "zookeeper"
    spec:
      containers:
      - name: "zookeeper"
        image: "{{ .Values.image.registry }}/{{ .Values.image.zooKeeper.repository }}:{{ .Values.image.zooKeeper.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.service.zooKeeper.port }}
        env:
        - name: "ZOOKEEPER_HOST_NAME"
          value: "zookeeper"
        - name: "ZOOKEEPER_CLIENT_PORT"
          value: "{{ .Values.service.zooKeeper.port }}"
        - name: "ZOOKEEPER_TICK_TIME"
          value: "2000"
        - name: "ZOOKEEPER_SERVER_ID"
          value: "1"
        {{- if .Values.resources }}
        resources:
          requests:
            memory: {{ .Values.resources.zooKeeper.requests.memory | quote }}
            cpu: {{ .Values.resources.zooKeeper.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.zooKeeper.limits.memory | quote }}
            cpu: {{ .Values.resources.zooKeeper.limits.cpu | quote }}
        {{- end}}
