---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "control-center"
  {{- if .Release.Namespace | ne "default" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- else if .Values.namespace | ne "default" }}
  namespace: {{ .Values.namespace | quote }}
  {{- end }}
  labels:
    app: "control-center"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "control-center"
  strategy: {}
  template:
    metadata:
      labels:
        app: "control-center"
    spec:
      containers:
      - name: "control-center"
        image: "{{ .Values.image.registry }}/{{ .Values.image.controlCenter.repository }}:{{ .Values.image.controlCenter.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.service.controlCenter.port }}
        {{- if .Values.resources }}
        resources:
          requests:
            memory: {{ .Values.resources.controlCenter.requests.memory | quote }}
            cpu: {{ .Values.resources.controlCenter.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.controlCenter.limits.memory | quote }}
            cpu: {{ .Values.resources.controlCenter.limits.cpu | quote }}
        {{- end }}
        env:
        - name: "CONFLUENT_METRICS_TOPIC_REPLICATION"
          value: "1"
        - name: "CONTROL_CENTER_BOOTSTRAP_SERVERS"
          value: "broker-1:9092,broker-2:9093,broker-3:9094"
        - name: "CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS"
          value: "1"
        - name: "CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS"
          value: "1"
        - name: "CONTROL_CENTER_REPLICATION_FACTOR"
          value: "1"
        - name: "CONTROL_CENTER_SCHEMA_REGISTRY_URL"
          value: "http://schema-registry:{{ .Values.service.schemaRegistry.port }}"
        - name: "CONTROL_CENTER_ZOOKEEPER_CONNECT"
          value: "zookeeper:{{ .Values.service.zooKeeper.port }}"
        - name: "PORT"
          value: "{{ .Values.service.controlCenter.port }}"
