---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "zookeeper"
  labels:
    app: "zookeeper"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "zookeeper"
  strategy: {}
  template:
    metadata:
      labels:
        app: "zookeeper"
    spec:
      containers:
      - name: "zookeeper"
        image: "{{ .Values.image.registry }}/{{ .Values.image.zooKeeper.repository }}:{{ .Values.image.zooKeeper.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 2181
        env:
        - name: "ZOOKEEPER_HOST_NAME"
          value: "zookeeper"
        - name: "ZOOKEEPER_CLIENT_PORT"
          value: "2181"
        - name: "ZOOKEEPER_TICK_TIME"
          value: "2000"
        - name: "ZOOKEEPER_SERVER_ID"
          value: "1"
        {{- if .Values.resources }}
        resources:
          requests:
            memory: {{ .Values.resources.zooKeeper.requests.memory | quote }}
            cpu: {{ .Values.resources.zooKeeper.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.zooKeeper.limits.memory | quote }}
            cpu: {{ .Values.resources.zooKeeper.limits.cpu | quote }}
        {{- end}}
