---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "broker-2"
spec:
  type: {{ .Values.service.broker2.type | quote }}
  ports:
  - port: {{ .Values.service.broker2.port }}
    targetPort: {{ .Values.service.broker2.port }}
    name: "broker-2"
  - port: {{ .Values.service.broker2.local }}
    targetPort: {{ .Values.service.broker2.local }}
    name: "broker-2-local"
  selector:
    app: "broker-2"
