---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "broker-3"
  {{- if .Release.Namespace | ne "default" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- else if .Values.namespace | ne "default" }}
  namespace: {{ .Values.namespace | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.broker3.type | quote }}
  ports:
  - port: {{ .Values.service.broker3.port }}
    targetPort: {{ .Values.service.broker3.port }}
    {{- if .Values.service.broker3.type | eq "NodePort" }}
    nodePort: {{ .Values.service.broker3.nodePort }}
    {{- end }}
    name: "broker-3"
  - port: {{ .Values.service.broker3.local }}
    targetPort: {{ .Values.service.broker3.local }}
    name: "broker-3-local"
  selector:
    app: "broker-3"
