---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "schema-registry"
  {{- if .Release.Namespace | ne "default" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- else if .Values.namespace | ne "default" }}
  namespace: {{ .Values.namespace | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.schemaRegistry.type }}
  ports:
  - port: {{ .Values.service.schemaRegistry.port }}
    targetPort: {{ .Values.service.schemaRegistry.port }}
    {{- if .Values.service.schemaRegistry.type | eq "NodePort" }}
    nodePort: {{ .Values.service.schemaRegistry.nodePort }}
    {{- end }}
    name: "schema-registry"
  selector:
    app: "schema-registry"
