---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "control-center"
  {{- if .Release.Namespace | ne "default" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- else if .Values.namespace | ne "default" }}
  namespace: {{ .Values.namespace | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.controlCenter.type }}
  ports:
  - port: {{ .Values.service.controlCenter.port }}
    targetPort: {{ .Values.service.controlCenter.port }}
    {{- if .Values.service.controlCenter.type | eq "NodePort" }}
    nodePort: {{ .Values.service.controlCenter.nodePort }}
    {{- end }}
    name: "control-center"
  selector:
    app: "control-center"
