---
services:
  neo4j-{{ release.name }}:
    image: "{{ values.image.repository }}:{{ values.image.tag }}"
    container_name: "neo4j-{{ release.name }}"
    ports:
      {% for port in values.service %}
      - "{{ port.node_port }}:{{ port.container_port }}"
      {% endfor %}
    environment:
      NEO4J_AUTH: "neo4j/{{ values.environment_variables.database_password }}"
    volumes:
      - "neo4j-data-{{ release.name }}:/data"
      - "neo4j-plugins-{{ release.name }}:/plugins"
