---
apiVersion: v1
kind: Service
metadata:
  name: batfish-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
    name: jupyter-nb
  - port: 9997
    targetPort: 9997
    name: java-1
  - port: 9996
    targetPort: 9996
    name: java-2
  selector:
    app: batfish
