---
apiVersion: v1
kind: Service
metadata:
  name: elk-lb
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    targetPort: 5601
    name: "kibana"
  - port: 9200
    targetPort: 9200
    name: "elastic-search"
  - port: 5044
    targetPort: 5044
    name: "logstash"
  selector:
    app: elk
