---
apiVersion: v1
kind: Service
metadata:
  name: elk-lb
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    targetPort: 5601
  - port: 9200
    targetPort: 9200
  - port: 5044
    targetPort: 5044
  selector:
    app: elk
