---
apiVersion: v1
kind: Service
metadata:
  name: batfish-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
  - port: 9997
    targetPort: 9997
  - port: 9996
    targetPort: 9996
  selector:
    app: batfish
