---
apiVersion: v1
kind: Service
metadata:
  name: registry-browser-service-nodeport
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8080
    nodePort: 31112
    protocol: TCP
  selector:
    app: registry-browser
