---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service-lb
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    name: mongo-db
  - port: 8081
    targetPort: 8081
    name: mongo-express-gui
  selector:
    app:
    - mongo
    - mongo-express
