---
version: '3.7'
services:
    vault:
        image: vault:latest
        hostname: vault
        container_name: vault
        ports:
            - "8200:8200"
        cap_add:
            - IPC_LOCK
        environment:
            VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
        volumes:
            - "vault-logs-compose:/vault/logs"
            - "vault-file-compose:/vault/file"

volumes:
    vault-logs-compose:
    vault-file-compose:
