---
version: '3.4'
services:
    elk:
        image: sebp/elk
        hostname: elk
        container_name: elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
