---
version: '3.7'
services:
    dev-vault:
        image: vault:latest
        container_name: dev-vault
        ports:
            - "10.0.0.102:8200:8200"
        cap_add:
            - IPC_LOCK
        environment:
            VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}},
"default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
        volumes:
            - ./vault:/vault/logs
            - ./vault:/vault/file
