version: '3.4'
services:
    registry:
        image: registry:2.7.1
        hostname: registry
        container_name: registry
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - "registry-storage-compose:/var/lib/registry"

volumes:
    registry-storage-compose:
