---
apiVersion: v1
kind: Service
metadata:
  name: influxdb2-service-nodeport
spec:
  type: NodePort
  ports:
  - port: 8086             # Port apps in cluster use
    targetPort: 8086       # Port to connect to container
    nodePort: 31120        # Port to expose on the nodes
    protocol: TCP
  selector:
    app: influxdb2
