FROM registry.access.redhat.com/ubi8/python-36

LABEL version="2021.6.2.001"
LABEL description="Genie Kafka Parser RHEL8"
LABEL maintainer="Ben Trachtenberg"

COPY ./genie-parser/docker_app_run /docker_app_run

WORKDIR /docker_app_run

RUN pip install --upgrade pip \
    && pip install --upgrade setuptools wheel \
    && pip install -r requirements.txt

ENTRYPOINT ["python", "docker_app_run.py"]
